<?php
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' | ');
    $this->headTitle('Тут бесплатные объявления');
    $this->headLink()->headLink(array('rel' => 'shortcut icon','href' => $this->baseUrl().'/images/favicon.ico', 'type' => 'image/x-icon'))
        ->headLink(array('rel' => 'stylesheet','href' => $this->baseUrl().'/css/reset.css', 'type' => 'text/css') ,'APPEND')
        ->headLink(array('rel' => 'stylesheet','href' => $this->baseUrl().'/css/style.css', 'type' => 'text/css') ,'APPEND')
        ->headLink(array('rel' => 'stylesheet','href' => $this->baseUrl().'/css/admin_style.css', 'type' => 'text/css') ,'APPEND');
    echo $this->doctype()."\n";
?>
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr">

<head>    
    <?php echo $this->headMeta()."\n"; ?>
    <?php echo $this->headTitle()."\n"; ?>
    <?php echo $this->headLink()."\n"; ?>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery.autosize-min.js"></script>
    <script type="text/javascript">
    $(function(){
        $('#description').autosize({append: "\n"});
    });
</script>
</head>
    <body>
        <!-- Container -->
        <div id="container">        
            <!-- Top -->
            <div class="top"> 
            	<!-- Logo -->
            	<a href="<?php echo $this->baseUrl(); ?>/">
                    <div id="logo">
                        <p>ТУТ</p>
                    </div>
                </a>
                <!-- /Logo -->
                
                <!-- Social Icons -->
                <ul class="socialicons">
                    <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
                    <li><p class="email"><?php echo Zend_Auth::getInstance()->getIdentity()->email; ?></p></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/account/messages" class="messages"></a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/account/ads" class="ads"></a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/account/settings" class="settings"></a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/account/signout" class="signout"></a></li>
                    <?php else: ?>
                    <li><a href="<?php echo $this->baseUrl(); ?>/account/signin" class="signin">Войти</a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/account/signup" class="signup">Зарегистрироваться</a></li>
                    <?php endif; ?>
                    <li><a href="http://facebook.com" class="social-facebook" target="_blank"></a></li>
                    <li><a href="http://twitter.com" class="social-twitter" target="_blank"></a></li>
                    <li><a href="http://plus.google.com" class="social-googleplus" target="_blank"></a></li>
                </ul>
                <!-- /Social Icons -->
            </div>
            <!-- /Top -->
            
            <!-- Content -->
            <div id="content" >
                <!-- Resume -->
                <div id="body">
                        <?php echo $this->layout()->content; ?>
                </div>
                <!-- /Resume -->
            </div>
            <!-- /Content -->
            
            <!-- Footer -->
            <div class="footer">
            	<div class="copyright">Copyright © <?php echo date("Y"); ?> Тут</div>
            </div>
            <!-- /Footer --> 
            
        </div>
        <!-- /Container -->
    </body>
</html>