<div class="email-change" style="width: 400px; margin-bottom: 30px">
    <form id="new" enctype="<?php echo $this->email->getEnctype(); ?>" action="<?php echo $this->email->getAction(); ?>" method="post">
<table>
    <tr>
        <td class="label"><p>Электронная почта</p></td>
        <td><?php echo $this->email->email; ?></td>
        <td><?php echo $this->email_error; ?></td>
    </tr>
    <tr>
        <td></td><td><?php echo $this->email->submit; ?></td>
    </tr>
</table>
</form>
</div>
<div class="email-change" style="width: 400px">
    <form id="new" enctype="<?php echo $this->password->getEnctype(); ?>" action="<?php echo $this->password->getAction(); ?>" method="post">
<table>
    <tr>
        <td class="label"><p>Нынешний пароль</p></td>
        <td><?php echo $this->password->old_password; ?></td>
    </tr>
    <tr>
        <td class="label">Новый пароль</td>
        <td><?php echo $this->password->password; ?></td>
    </tr>
    <tr>
        <td class="label">Повторите новый пароль</td>
        <td><?php echo $this->password->password_confirm; ?></td>
        <td><?php echo $this->pass_error; ?></td>
    </tr>
    <tr>
        <td></td><td><?php echo $this->password->submit; ?></td>
    </tr>
</table>
</form>
</div>