<div class="signin-box">
<?php if(isset($this->errMessage)){echo $this->errMessage;} ?>
<form id="new" enctype="<?php echo $this->signin->getEnctype(); ?>" action="<?php echo $this->signin->getAction(); ?>" method="post">
<table>
    <tr>
        <td class="label"><p>Электронная почта</p></td><td><?php echo $this->signin->email; ?></td>
    </tr>
    <tr>
        <td class="label">Пароль</td><td><?php echo $this->signin->password; ?></td>
    </tr>
    <tr>
        <td></td><td><?php echo $this->signin->submit; ?></td>
    </tr>
</table>
</form>
</div>
<div class="signin-box" style="padding: 72px 69px;">
    <input type="submit" value="Войти с помощью facebook">
</div>