<form id="new" enctype="application/x-www-form-urlencoded" action="" method="post">
<table>
    <tr>
        <td class="signup-label"><p>Электронная почта</p></td><td><?php echo $this->signup->email; ?></td>
    </tr>
    <tr>
        <td>Пароль</td><td><?php echo $this->signup->password; ?></td>
    </tr>
    <tr>
        <td>Повторите пароль</td><td><?php echo $this->signup->password_confirm; ?></td>
    </tr>
    <tr>
        <td></td><td><?php echo $this->signup->submit; ?></td>
    </tr>
</table>
</form>