<div class="main-section">
    <h3 style="margin-bottom: 10px;"><?php echo $this->ad->title; ?></h3>
    <div class="ad-image-box">
        <div class="ad-image">
            <img src="./images/img_1.jpg"/>
        </div>
        <div class="ad-thumb-box">
            <ul class="ad-thumb">
                <?php for($i=1;$i<5;$i++): ?>
                <li>
                    <a href="./images/img_<?php echo $i; ?>.jpg" onclick="galery(this.href); return false;">
                        <img src="images/img_mini_<?php echo $i; ?>.jpg"/>
                    </a>
                </li>
                <?php endfor; ?>
            </ul>
        </div>
    </div>
    <div class="description" style="margin-top: 20px">
        <p><?php echo $this->ad->description; ?></p>
    </div>
</div>
<script type="text/javascript">
    function galery(url){
        $(".ad-image").html("<img src='"+url+"'/>");
    }
</script>