<?php if(isset($this->subcat_list))foreach($this->subcat_list as $value): ?>
<a id="<?php echo $value["id"]; ?>" href="<?php echo $this->baseUrl().'/ad/list?subcategory='.$value["id"]; ?>">
    <?php echo $value["name"]; ?>
</a>
<?php endforeach; ?>

<?php if(isset($this->adlist))foreach($this->adlist as $value): ?>
<div class="ad-list">
    <a href="<?php echo $this->baseUrl(); ?>/ad?id=<?php echo $value["id"]; ?>">
        <div class="ad-list-image">
            <img src="<?php echo $this->baseUrl(); ?>/images/manas.jpg"/>
        </div>
        <div class="ad-list-text">
            <strong><?php echo $value["title"]; ?></strong>
            <p>Цена</p>
            <p>Категория и подкатегория</p>
        </div>
    </a>
</div>
<?php endforeach; ?>
