
    <div class="right-section">
        <a href="<?php echo $this->baseUrl(); ?>/ad/new"><input type="submit" value="+ Новое объявление" class="add-ad-button"/></a>
        <div class="real-ad-style">
            <div class="real-ad-style-top">
            <a href="<?php echo $this->baseUrl(); ?>/account/signin">Вход</a> /
            <a href="<?php echo $this->baseUrl(); ?>/account/signup">Регистрация</a>
            <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
            <p><?php echo Zend_Auth::getInstance()->getIdentity()->user_email; ?></p>
            <a href="<?php echo $this->baseUrl(); ?>/account/signout">Выход</a>
            <?php endif; ?>
            </div>
            <ul>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>
    </div>