<div class="main-section">
    <form enctype="multipart/form-data" method="GET" action="<?php echo $this->baseUrl(); ?>/search" style="margin-bottom: 10px;">
        <input type="text" name="q" id="main-search" placeholder="Поиск объявлений..." autocomplete="off"/>
        <input type="submit" class="search-button" value="Поиск"/>
    </form>

    <ul id="da-thumbs" class="da-thumbs">
        <?php if(isset($this->cat_list))foreach($this->cat_list as $value): ?>
            <a href="<?php echo $this->baseUrl().'/ads/list?category='.$value["id"]; ?>">
                <li>
                    <div class="cat-name">
                         <img src="<?php echo $this->baseUrl(); ?>/images/thumb.jpg"/> 
                    </div>
                    <p class="cat-title"><?php echo $value["name"]; ?></p>
                </li>
            </a>
        <?php endforeach; ?>
    </ul>
</div>

<div class="right-section">
    <?php echo $this->render("right.phtml");?>
</div>